version: "3.9"
services:
  python-image-dev:
    container_name: python-env
    build:
      context: .
      dockerfile: docker/Dockerfile-python-dev
    ports: 
      - "8888:8888"
    volumes:
      - type: bind
        source: .
        target: /home/jovyan
    environment:
        GRANT_SUDO: "yes"
  postgres-image-dev:
    container_name: postgres-env
    image: postgres:10
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: postgres
