FROM jupyter/base-notebook:python-3.8.3

USER root

RUN apt-get update && \
    apt-get install -y \
        ssh \
        nano \
        git \
        vim \ 
        # chromium-browser \
        libaio1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN rm requirements.txt

# USER jovyan        